spring:
  kafka:
    schema:
      registry:
        url: http://schema-registry:8081
    consumer:
      bootstrap-servers: PLAINTEXT://broker:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: PLAINTEXT://broker:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer